from unittest import TestCase

import solutions.day08

TEST_DATA = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''


class TestDay08(TestCase):
    def test_part08(self):
        expected = 14
        solver = solutions.day08.Solver(rawData=TEST_DATA)

        self.assertEqual(expected, solver.SolvePartOne())

    def test_part02(self):
        simpleCase = '''T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........'''

        simpleExpected = 9
        solver = solutions.day08.Solver(rawData=simpleCase)
        self.assertEqual(simpleExpected, solver.SolvePartTwo())

        expected = 34
        solver = solutions.day08.Solver(rawData=TEST_DATA)

        self.assertEqual(expected, solver.SolvePartTwo())
